"""initial_schema

Revision ID: 2ec414f6c3f4
Revises: 
Create Date: 2026-05-31 12:28:37.300607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec414f6c3f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_insights', sa.Column('sdnn', sa.Float(), nullable=True))
    op.add_column('medical_insights', sa.Column('pnn50', sa.Float(), nullable=True))
    op.add_column('physicians', sa.Column('email', sa.String(), nullable=True))
    op.add_column('physicians', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'physicians', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'physicians', type_='unique')
    op.drop_column('physicians', 'hashed_password')
    op.drop_column('physicians', 'email')
    op.drop_column('medical_insights', 'pnn50')
    op.drop_column('medical_insights', 'sdnn')
    # ### end Alembic commands ###
